service: covid-business-grants

provider:
  name: aws
  region: eu-west-2
  stage: ${opt:stage}
  dbname: covidBusinessGrantsDbUpdated
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:ListBucket
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

resources:
  Resources:
    covidBusinessGrantsSupportingDocumentsBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
          BucketName: ${self:custom.bucket}
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          CorsConfiguration:
            CorsRules:
              -
                AllowedOrigins:
                  - '*'
                AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - PUT
                  - POST
                MaxAge: 3000
    covidBusinessGrantsDbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Access to Postgres
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 0.0.0.0/0
        VpcId: ${self:custom.vpcs.${self:provider.stage}}

    covidBusinessGrantsRDSSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds: ${self:custom.subnets.${self:provider.stage}}

    covidBusinessGrantsDbUpdated:
      Type: AWS::RDS::DBInstance
      DBSnapshotIdentifier: ${self:custom.rds-snapshot.${self:provider.stage}}
      Properties:
        AllocatedStorage: 5
        DBInstanceIdentifier: "covid-business-grants-db-${self:provider.stage}"
        DBInstanceClass: "db.t2.small"
        # DBName: ${self:provider.dbname}
        DeletionProtection: false
        Engine: "postgres"
        EngineVersion: "11.12"
        MasterUsername: ${env:MASTER_USERNAME}
        MasterUserPassword: ${env:MASTER_USER_PASSWORD}
        MultiAZ: true
        PubliclyAccessible: false
        StorageEncrypted: true
        VPCSecurityGroups:
        - Fn::GetAtt:
          - covidBusinessGrantsDbSecurityGroup
          - GroupId
        DBSubnetGroupName:
          Ref: covidBusinessGrantsRDSSubnetGroup
        Tags:
          -
            Key: "Name"
            Value: "covidBusinessGrantsDbUpdated"
      DeletionPolicy: Delete

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.aliases.${self:provider.stage}}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.certificate-arn.${self:provider.stage}}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  # bucket: ${self:service}-supporting-documents-${self:provider.stage}
  bucket: ${self:service}-regen-supporting-documents-${self:provider.stage}
  rds-snapshot:
    staging: arn:aws:rds:eu-west-2:647298111750:snapshot:restored-grants-db
    production: arn:aws:rds:eu-west-2:812721144296:snapshot:cbg-snapshot-final
  domain-name:
    Fn::Join:
      - '.'
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  aliases:
    staging: staging-covidbusinessgrants.hackney.gov.uk
    production: covidbusinessgrants.hackney.gov.uk
  certificate-arn:
    staging: arn:aws:acm:us-east-1:647298111750:certificate/a9c099b9-50bb-411b-84e3-982ffa1c76bf
    production: arn:aws:acm:us-east-1:812721144296:certificate/f0ad1b83-2a2d-4073-9a1e-fc614fa2eb94
  vpcs:
    staging: vpc-0047c1ec06d524b64
    production: vpc-0c9c2cbf1865adb9e
  subnets:
    staging:
      - subnet-034d259953e54531a
      - subnet-0e0152a2fc2b42498
    production:
      - subnet-067865bb76395b74e
      - subnet-056356c011224f114
  allowed-groups:
    staging: 'Covid Business Grants (Mandatory) - Staging'
    production: 'Covid Business Grants (Mandatory)'