service: covid-business-grants

provider:
  name: aws
  region: eu-west-2
  stage: ${opt:stage}
  dbname: covidBusinessGrantsDbUpdated
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:ListBucket
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

resources:
  Resources:
    covidBusinessGrantsSupportingDocumentsBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
          BucketName: ${self:custom.bucket}
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          CorsConfiguration:
            CorsRules:
              -
                AllowedOrigins:
                  - '*'
                AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - PUT
                  - POST
                MaxAge: 3000
    covidBusinessGrantsDbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Access to Postgres
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 0.0.0.0/0
        VpcId: ${self:custom.vpcs.${self:provider.stage}}

    covidBusinessGrantsRDSSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds: ${self:custom.subnets.${self:provider.stage}}

    covidBusinessGrantsDbUpdated:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 5
        DBInstanceIdentifier: "covid-business-grants-db-${self:provider.stage}-updated"
        CACertificateIdentifier: 'rds-ca-rsa2048-g1'
        DBInstanceClass: "db.t3.small"
        DBName: ${self:provider.dbname}
        DeletionProtection: false
        Engine: "postgres"
        EngineVersion: "11.22"
        MasterUsername: ${env:MASTER_USERNAME}
        MasterUserPassword: ${env:MASTER_USER_PASSWORD}
        MultiAZ: true
        PubliclyAccessible: false
        StorageEncrypted: true
        VPCSecurityGroups:
        - Fn::GetAtt:
          - covidBusinessGrantsDbSecurityGroup
          - GroupId
        DBSubnetGroupName:
          Ref: covidBusinessGrantsRDSSubnetGroup
        Tags:
          - Key: "Name"
            Value: "covidBusinessGrantsDbUpdated"
          - Key: "BackupPolicy"
            Value: "Prod"
          - Key: "STAGE"
            Value: ${self:provider.stage}
      DeletionPolicy: Delete

custom:
  # bucket: ${self:service}-supporting-documents-${self:provider.stage}
  bucket: ${self:service}-regen-supporting-documents-${self:provider.stage}
  rds-snapshot:
    staging: arn:aws:rds:eu-west-2:647298111750:snapshot:restored-grants-db
    production: arn:aws:rds:eu-west-2:812721144296:snapshot:cbg-snapshot-final
  vpcs:
    staging: vpc-0047c1ec06d524b64
    production: vpc-0c9c2cbf1865adb9e
  subnets:
    staging:
      - subnet-034d259953e54531a
      - subnet-0e0152a2fc2b42498
    production:
      - subnet-067865bb76395b74e
      - subnet-056356c011224f114
