version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  node-executor:
    docker:
      - image: circleci/node:16.9.1-browsers
  docker-python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build-deploy-production:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - aws-cli/install
      - checkout
      - run:
          name: install
          command: sudo npm i -g serverless@^3
      - run:
          name: deploy
          command:
            # sls remove --verbose --stage production
            
            bucket_name="covid-business-grants-pr-serverlessdeploymentbuck-193fpskx8va0u"
            aws s3 rm "s3://$bucket_name" --recursive
            aws s3api delete-bucket --bucket $bucket_name
          no_output_timeout: 45m

  assume-role-production:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_REGEN_APPS_PRODUCTION
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - permit-deploy-production:
          type: approval
          filters:
            branches:
              only: master
      - are-you-sure:
          type: approval
          requires:
            - permit-deploy-production
          filters:
            branches:
              only: master
      - assume-role-production:
          context: api-assume-role-regen-apps-production-context
          requires:
            - are-you-sure
          filters:
            branches:
              only: master
      - build-deploy-production:
          requires:
            - are-you-sure
            - assume-role-production
          filters:
            branches:
              only: master
