version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  node-executor:
    docker:
      - image: circleci/node:16.9.1-browsers
  docker-python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build-deploy-production:
    executor: node-executor
    steps:
      - *attach_workspace
      - run:
          name: deploy
          command: yarn build && yarn --production=true && sudo npm i -g serverless@^3 && sls deploy --stage production
          no_output_timeout: 45m

  assume-role-production:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_REGEN_APPS_PRODUCTION
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

workflows:
  version: 2
  continuous-delivery:
    jobs:
      # - install-dependencies-and-test
      - permit-deploy-staging:
          type: approval
          # requires:
          #   - install-dependencies-and-test
          # filters:
          #   branches:
          #     only:
          #       - master
      - assume-role-staging:
          context: api-assume-role-regen-apps-staging-context
          requires:
            - permit-deploy-staging
          # filters:
          #   branches:
          #     only: master
      - build-deploy-delete-staging:
          requires:
            # - install-dependencies-and-test
            - assume-role-staging
          # filters:
          #   branches:
          #     only:
          #       - master
      - permit-deploy-production:
          type: approval
          requires:
            - build-deploy-delete-staging
      - are-you-sure:
          type: approval
          requires:
            - permit-deploy-production
      - assume-role-production:
          context: api-cloud-engineering-deployment-context
          requires:
            # - install-dependencies-and-test
            - are-you-sure
          filters:
            branches:
              only: master
      - build-deploy-production:
          requires:
            - are-you-sure
            - assume-role-production
