ALTER TABLE eligibility_criteria_details DROP COLUMN trading_on_30_11_20;
ALTER TABLE eligibility_criteria_details DROP COLUMN trading_on_01_12_20;
ALTER TABLE eligibility_criteria_details DROP COLUMN trading_on_15_12_20;
ALTER TABLE eligibility_criteria_details DROP COLUMN trading_on_19_12_20;

ALTER TABLE application_assessment DROP COLUMN csp_amount;
ALTER TABLE application_assessment DROP COLUMN lrsg_closed_tier_2_amount;
ALTER TABLE application_assessment DROP COLUMN lrsg_closed_tier_3_amount;
ALTER TABLE application_assessment DROP COLUMN lrsg_closed_tier_4_amount;

ALTER TABLE application_assessment DROP COLUMN csp_payment_exported;
ALTER TABLE application_assessment DROP COLUMN lrsg_closed_tier_2_payment_exported;
ALTER TABLE application_assessment DROP COLUMN lrsg_closed_tier_3_payment_exported;
ALTER TABLE application_assessment DROP COLUMN lrsg_closed_tier_4_payment_exported;
